---
- name: install required packages
  become: true
  apt:
    name:
      - bzip2

- name: make cp2k directories
  become: true
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ cp2k_bin_dir }}"
    - "{{ cp2k_data_dir }}"

- name: download cp2k binary
  become: true
  get_url:
    url: "{{ cp2k_release_url }}/{{ item.download }}"
    dest: "{{ cp2k_bin_dir }}/{{ item.executable }}"
    mode: '0755'
  with_items: "{{ cp2k_executables }}"

# - name: symlink binary
#   file:
#     src: "{{ cp2k_topdir }}/exe/{{ cp2k_binary }}"
#     dest: "{{ cp2k_topdir }}/exe/cp2k.ssmp"
#     state: link

- name: download cp2k data files
  become: true
  get_url:
    url: "{{ cp2k_git_url }}/data/{{ item }}"
    dest: "{{ cp2k_data_dir }}/"
    # for some reason, the first item used to time out
    # with the default timeout of 10s
    timeout: 30
  with_items:
    - BASIS_MOLOPT
    - POTENTIAL
    - ALL_BASIS_SETS
    - ALL_POTENTIALS

- name: download copyright notice
  become: true
  get_url:
    url: "{{ cp2k_git_url }}/{{ item }}"
    dest: "{{ cp2k_data_dir }}"
  with_items:
    - COPYRIGHT

- name: "Add CP2K_DATA_DIR environment variable"
  become: true
  lineinfile:
    path: "{{ cp2k_env_file }}"
    line: "export CP2K_DATA_DIR={{ cp2k_data_dir }}"
    create: true

- name: "Add environment variable for ASE"
  become: true
  lineinfile:
    path: "{{ cp2k_env_file }}"
    line: "export ASE_CP2K_COMMAND=cp2k.ssmp --shell"
    create: true

- include_role:
    name: release_notes
  vars:
    section: "cp2k"
    option: "usage"
    value: >-
      cp2k binary was downloaded from source forge.
      simply run 'cp2k.ssmp'
  when: release_notes is defined and release_notes
