---
- name: install required packages
  become: true
  become_user: "{{ root_user }}"
  apt:
    name:
      - bzip2

- name: make cp2k directories
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ cp2k_topdir }}/exe"
    - "{{ cp2k_topdir }}/data"

- name: download cp2k binary
  get_url:
    url: "{{ cp2k_release_url }}/{{ item.download }}"
    dest: "{{ cp2k_topdir }}/exe/{{ item.executable }}"
    mode: "u+x"
  with_items: "{{ cp2k_executables }}"

# - name: symlink binary
#   file:
#     src: "{{ cp2k_topdir }}/exe/{{ cp2k_binary }}"
#     dest: "{{ cp2k_topdir }}/exe/cp2k.ssmp"
#     state: link

- name: download cp2k data files
  get_url:
    url: "{{ cp2k_git_url }}/data/{{ item }}"
    dest: "{{ cp2k_topdir }}/data/"
    # for some reason, the first item used to time out
    # with the default timeout of 10s
    timeout: 30
  with_items:
    - BASIS_MOLOPT
    - POTENTIAL
    - ALL_BASIS_SETS
    - ALL_POTENTIALS

- name: download copyright notice
  get_url:
    url: "{{ cp2k_git_url }}/{{ item }}"
    dest: "{{ cp2k_topdir }}"
  with_items:
    - COPYRIGHT

- name: "Put a line in ~/.profile to add cp2k to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ cp2k_topdir }}/exe"

- name: "Put a line in ~/.profile for cp2k data directory"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export CP2K_DATA_DIR={{ cp2k_topdir }}/data"

- include_role:
    name: release_notes
  vars:
    section: "cp2k"
    option: "usage"
    value: >-
      cp2k binary was downloaded from source forge.
      simply run 'cp2k.ssmp'
  when: release_notes is defined and release_notes
