- import_tasks: install_via_apt.yml
  when: cp2k_installation_route == 'apt'
- import_tasks: install_via_make.yml
  when: cp2k_installation_route == 'make'
- import_tasks: download_binary.yml
  when: cp2k_installation_route == 'download'

- include_role:
    name: release_notes
  vars:
    section: "cp2k"
    option: "version"
    value: "{{ cp2k_version }}"
  when: release_notes is defined and release_notes
